name: Deploy workflow

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run test-component

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        env:
          Deploy_URL: ${{ secrets.RENDER_DEPLOY_URL }}
        run: |
          echo "Deploying to Render..."
          curl "$Deploy_URL"
